export const AUTH_LOADING = "AUTH_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";

export const IS_LOADING="IS_LOADING"

// log-in
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// Sign-Up

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERRORS = "SIGNUP_ERRORS";

// otp
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_ERRORS = "OTP_ERRORS";

// RE_otp
export const RE_OTP_LOADING = "RE_OTP_LOADING";
export const RE_OTP_SUCCESS = "RE_OTP_SUCCESS";
export const RE_OTP_ERRORS = "RE_OTP_ERRORS";
// FORGOT_PASSWORD

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

// RESET_PASSWORD
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

//  LOGOUT_SUCCESS

export const LOGOUT_SUCCESS = " LOGOUT_SUCCESS";

// CHANGE_PASSWORD

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

//CATEGORY_LIST
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";

//SUB_CATEGORY_LIST
export const SUB_CATEOGRY_LIST_SUCCESS = "SUB_CATEOGRY_LIST_SUCCESS";
export const SUB_CATEOGRY_LIST_ERROR = "SUB_CATEOGRY_LIST_ERROR";

//SCHOOL_LIST
export const SCHOOL_LIST_SUCCESS = "SCHOOL_LIST_SUCCESS";
export const SCHOOL_LIST_ERROR = "SCHOOL_LIST_ERROR";

//COURSE_LIST
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_ERROR = "COURSE_LIST_ERROR";


//SUBJECT_LIST
export const SUBJECT_LIST_SUCCESS = "SUBJECT_LIST_SUCCESS";
export const SUBJECT_LIST_ERROR = "SUBJECT_LIST_ERROR";

//COUNTRY_LIST
export const COUNTRY_LIST_SUCCESS = "COUNTRY_LIST_SUCCESS";
export const COUNTRY_LIST_ERROR = "COUNTRY_LIST_ERROR";

//STATE_LIST
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_ERROR = "STATE_LIST_ERROR";


//BANNER_LIST
export const BANNER_LIST_SUCCESS = "BANNER_LIST_SUCCESS";
export const BANNER_LIST_ERROR = "BANNER_LIST_ERROR";